// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: 'us-east-2',
	aws_dynamodb_all_tables_region: 'us-east-2',
	aws_dynamodb_table_schemas: [
		{
			tableName: 'dynamo6f759d98-one',
			region: 'us-east-2',
		},
	],
	aws_cognito_identity_pool_id:
		'us-east-2:86d102b9-8681-44e0-a3d2-a98617a583b5',
	aws_cognito_region: 'us-east-2',
	aws_user_pools_id: 'us-east-2_QTfv5W1zU',
	aws_user_pools_web_client_id: '32pjjhn786fmujq4fvkpp954ie',
	oauth: {},
	aws_cloud_logic_custom: [
		{
			name: 'api5236abc9',
			endpoint: 'https://t8jwjklkrc.execute-api.us-east-2.amazonaws.com/one',
			region: 'us-east-2',
		},
	],
};

export default awsmobile;
